import React, { useState, useEffect, useRef } from 'react';
import { analyzeIPO } from '../../services/deepSeekService';
import { IPOAnalysis } from '../../types';
import HealthCard from '../../components/HealthCard';
import ScoringCard from '../../components/ScoringCard';
import DecisionCard from '../../components/DecisionCard';
import TradingPlanCard from '../../components/TradingPlanCard';
import ScenarioTable from '../../components/ScenarioTable';
import LiquidityRiskCard from '../../components/LiquidityRiskCard';
import ValuationCard from '../../components/ValuationCard';
import IPORadar from '../../components/IPORadar';
import SkeletonDashboard from '../../components/SkeletonDashboard';
import CapitalStructureCard from '../../components/CapitalStructureCard';
import ResearchAssistant from '../../components/ResearchAssistant';
import { useAuth, UserTier } from '../context/AuthContext';
import { supabase } from '../lib/supabase';
import { Link, useNavigate } from 'react-router-dom';

// --- Export Helper Functions ---

const downloadFile = (content: string, filename: string, mimeType: string) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
};

const generateMarkdown = (data: IPOAnalysis) => {
    return `
# ${data.companyName} (${data.stockCode}) - IPO Decision Report
**Date:** ${data.lastUpdated} | **Sector:** ${data.sector} | **Price:** ${data.priceRange}

## 1. Executive Summary
- **Decision:** ${data.positionAdvice.recommendation}
- **Score:** ${data.scoring.totalScore} / 100
- **Summary:** ${data.scoring.summary}

## 2. IPO Radar (Screening & Sentiment)
- **Sentiment:** ${data.ipoRadar?.marketSentiment?.sentimentTrend} (Score: ${data.ipoRadar?.marketSentiment?.sentimentScore})
- **Tags:** ${data.ipoRadar?.screeningMetrics?.keyTags.join(', ')}

## 3. Smart Core Radar (Liquidity & Risk)
- **Anchor Heat:** ${data.liquidityAnalysis?.anchorHeatIndex?.score} (${data.liquidityAnalysis?.anchorHeatIndex?.status})
- **Lock-up Risk:** ${data.liquidityAnalysis?.lockUpRisk?.riskLevel}
- **Retail Sentiment:** ${data.liquidityAnalysis?.retailSentiment?.clawbackPrediction}

## 4. Capital Structure & Issuance
- **Total Shares:** ${data.issuanceInfo?.totalShares}
- **Cornerstone %:** ${data.issuanceInfo?.cornerstonePctOfOffer}
- **Cornerstones:** ${data.cornerstones?.map(c => c.name).join(', ') || 'N/A'}

## 5. Risk & Compliance
- **Health Check Status:** ${data.healthCheck.every(h => h.status === 'GREEN') ? 'All Clear' : 'Issues Found'}
- **Issues:** ${data.healthCheck.filter(h => h.status !== 'GREEN').map(h => h.label).join(', ')}

## 6. Business & Fundamentals
- **Description:** ${data.business.description}
- **Products:** ${data.business.mainProducts.join(', ')}
- **Position:** ${data.business.industryPosition}

## 7. Financials
- **CAGR:** ${data.financials.cagr || 'N/A'}
- **Revenue Structure:** ${data.financials.revenueStructure?.join(', ') || 'N/A'}

## 8. Valuation
- **Fair Value:** ${data.valuation?.fairValueRange}
- **Fair Price:** ${data.valuation?.fairPrice || 'N/A'}
- **Peers:** ${data.valuation?.peers?.map(p => p.ticker).join(', ')}

## 9. Exit Strategies
${data.exitStrategies?.map(s => `### ${s.investorType}\n- Action: ${s.primaryAction}\n- Stop/Hedge: ${s.stopLossOrHedge}`).join('\n\n')}

---
*Generated by HK IPO Decision Engine*
`.trim();
};

const generateWordHTML = (data: IPOAnalysis) => {
    return `
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
    <head><meta charset='utf-8'><title>${data.companyName} Report</title>
    <style>body { font-family: 'Arial', sans-serif; }</style>
    </head><body>
    <h1>${data.companyName} (${data.stockCode})</h1>
    <p><strong>Date:</strong> ${data.lastUpdated}</p>
    <hr/>
    <h2>1. Executive Summary</h2>
    <p><strong>Recommendation:</strong> <span style="color:${data.positionAdvice.recommendation === 'GO' ? 'green' : 'red'}">${data.positionAdvice.recommendation}</span></p>
    <p><strong>Total Score:</strong> ${data.scoring.totalScore}</p>
    
    <h2>2. IPO Radar</h2>
    <p><strong>Sentiment:</strong> ${data.ipoRadar?.marketSentiment?.sentimentTrend}</p>
    <p><strong>Key Tags:</strong> ${data.ipoRadar?.screeningMetrics?.keyTags.join(', ')}</p>

    <h2>3. Liquidity & Risk</h2>
    <p><strong>Anchor Heat:</strong> ${data.liquidityAnalysis?.anchorHeatIndex?.score}</p>
    <p><strong>Lock-up Risk:</strong> ${data.liquidityAnalysis?.lockUpRisk?.sellingPressure}</p>
    
    <h2>4. Capital Structure</h2>
    <p><strong>Total Shares:</strong> ${data.issuanceInfo?.totalShares}</p>
    <p><strong>Cornerstone %:</strong> ${data.issuanceInfo?.cornerstonePctOfOffer}</p>

    <h2>5. Risk & Compliance</h2>
    <p><strong>Issues Found:</strong> ${data.healthCheck.filter(h => h.status !== 'GREEN').length}</p>

    <h2>6. Business & Financials</h2>
    <p><strong>Business:</strong> ${data.business.description}</p>
    <p><strong>CAGR:</strong> ${data.financials.cagr}</p>
    
    <h2>7. Valuation</h2>
    <p><strong>Range:</strong> ${data.valuation?.fairValueRange}</p>
    <p><strong>Pricing:</strong> ${data.valuation?.fairPrice}</p>
    
    <h2>8. Exit Strategies</h2>
    ${data.exitStrategies?.map(s => `
      <h3>${s.investorType}</h3>
      <p><strong>Action:</strong> ${s.primaryAction}</p>
      <p><strong>Risk Control:</strong> ${s.stopLossOrHedge}</p>
    `).join('')}
    </body></html>
  `;
};

// --- Sub-Components for Layout ---

const NavItem = ({ label, id, active }: { label: string, id: string, active: boolean }) => (
    <a
        href={`#${id}`}
        className={`block px-4 py-2 text-sm font-medium rounded-md transition-colors duration-200 ${active
            ? 'bg-blue-50 text-blue-700 border-l-4 border-blue-600'
            : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'
            }`}
    >
        {label}
    </a>
);

// --- Main Component ---

// --- Pro Guard Component ---
const ProLock = ({ tier, children }: { tier?: UserTier, children: React.ReactNode }) => {
    if (tier === 'pro') return <>{children}</>;
    return (
        <div className="relative overflow-hidden rounded-xl border border-gray-200 min-h-[300px]">
            <div className="filter blur-sm select-none pointer-events-none opacity-50 p-6">
                {children || <div className="h-64 bg-gray-50/50 rounded-lg animate-pulse" />}
            </div>
            <div className="absolute inset-0 z-10 flex flex-col items-center justify-center bg-white/60 backdrop-blur-[2px]">
                <div className="bg-white p-6 rounded-2xl shadow-xl text-center max-w-sm border border-indigo-100">
                    <div className="mx-auto w-12 h-12 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-full flex items-center justify-center mb-4">
                        <svg className="w-6 h-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
                        </svg>
                    </div>
                    <h3 className="text-lg font-bold text-gray-900 mb-1">Pro 版功能</h3>
                    <p className="text-gray-500 text-sm mb-4">升级会员以解锁深度流动性分析、财务建模及退出策略。</p>
                    <button className="px-6 py-2 bg-slate-900 text-white text-sm font-bold rounded-full hover:bg-slate-800 transition-colors">
                        立即升级
                    </button>
                </div>
            </div>
        </div>
    );
};

// --- Main Component ---

const Dashboard: React.FC = () => {
    const [companyName, setCompanyName] = useState('');
    const [subscriptionMultiple, setSubscriptionMultiple] = useState('');
    const [prospectusUrlInput, setProspectusUrlInput] = useState('');
    const [selectedFile, setSelectedFile] = useState<File | null>(null);
    const [data, setData] = useState<IPOAnalysis | null>(null);
    const [loading, setLoading] = useState(false);
    const [loadingMessage, setLoadingMessage] = useState('初始化分析引擎...');
    const [error, setError] = useState<string | null>(null);
    const [activeSection, setActiveSection] = useState('summary');

    const [history, setHistory] = useState<IPOAnalysis[]>([]);
    const [showHistory, setShowHistory] = useState(false);

    const progressTimer = useRef<ReturnType<typeof setInterval> | null>(null);

    // Auth Context
    const { user, profile, signOut, loading: authLoading } = useAuth();
    const navigate = useNavigate();

    // Redirect if not logged in
    useEffect(() => {
        if (!authLoading && !user) {
            navigate('/login');
        }
    }, [user, authLoading, navigate]);

    // Welcome Notification
    const [showWelcome, setShowWelcome] = useState(false);
    useEffect(() => {
        if (!authLoading && user) {
            // Simple check: show welcome if not historically dismissed (session storage)
            // For demo purposes, we show it on every fresh load if session is active
            const hasSeenRequest = sessionStorage.getItem('hasSeenWelcome');
            if (!hasSeenRequest) {
                setShowWelcome(true);
                sessionStorage.setItem('hasSeenWelcome', 'true');
                // Auto hide after 5s
                setTimeout(() => setShowWelcome(false), 5000);
            }
        }
    }, [user, authLoading]);

    // Load History on Mount
    useEffect(() => {
        const saved = localStorage.getItem('ipo_history');
        if (saved) {
            try {
                setHistory(JSON.parse(saved));
            } catch (e) {
                console.error("Failed to parse history");
            }
        }
    }, []);

    // Scroll Spy for Active Section
    useEffect(() => {
        const handleScroll = () => {
            const sections = ['summary', 'radar', 'liquidity', 'capital', 'risks', 'business', 'financials', 'valuation', 'scenarios', 'exit'];
            for (const section of sections) {
                const element = document.getElementById(section);
                if (element) {
                    const rect = element.getBoundingClientRect();
                    if (rect.top >= 0 && rect.top <= 300) {
                        setActiveSection(section);
                        break;
                    }
                }
            }
        };
        window.addEventListener('scroll', handleScroll);
        return () => window.removeEventListener('scroll', handleScroll);
    }, []);

    // Save to History Helper
    const saveToHistory = (newItem: IPOAnalysis) => {
        const newHistory = [newItem, ...history.filter(h => h.companyName !== newItem.companyName)].slice(0, 20); // Keep last 20 unique
        setHistory(newHistory);
        localStorage.setItem('ipo_history', JSON.stringify(newHistory));
    };

    const deleteHistoryItem = (index: number, e: React.MouseEvent) => {
        e.stopPropagation();
        const newHistory = history.filter((_, i) => i !== index);
        setHistory(newHistory);
        localStorage.setItem('ipo_history', JSON.stringify(newHistory));
    };

    const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files && e.target.files[0]) {
            setSelectedFile(e.target.files[0]);
        }
    };

    const startProgressSimulation = () => {
        const stages = [
            "正在解析招股书关键数据 (Parsing Data)...",
            "正在进行财务与估值建模 (Valuation Modeling)...",
            "正在生成机构投资策略 (Generating Strategy)...",
            "正在生成最终决策报告 (Finalizing Report)..."
        ];
        let step = 0;

        // Clear existing timer if any
        if (progressTimer.current) clearInterval(progressTimer.current);

        progressTimer.current = setInterval(() => {
            if (step < stages.length) {
                setLoadingMessage(stages[step]);
                step++;
            }
        }, 4000); // Update message every 4 seconds
    };

    const stopProgressSimulation = () => {
        if (progressTimer.current) {
            clearInterval(progressTimer.current);
            progressTimer.current = null;
        }
    };

    const handleAnalyze = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!companyName.trim()) return;

        setLoading(true);
        setError(null);
        setData(null);
        setShowHistory(false);

        // Initial message
        setLoadingMessage("正在初始化分析引擎 (Initializing)...");

        try {
            const subMult = subscriptionMultiple.trim() || "未知 (Unknown)";

            // [Antigravity Idea]: Log Search ATTEMPT immediately so Admin can see activity even if AI fails/throttles
            if (user) {
                supabase.from('search_logs').insert([
                    {
                        user_id: user.id,
                        company_name: companyName, // Use input name
                        stock_code: prospectusUrlInput.includes('hkex') ? 'Pending' : ''
                    }
                ]).then(({ error }) => {
                    if (error) console.error("Failed to log search attempt:", error);
                });
            }

            const result = await analyzeIPO(
                companyName,
                subMult,
                selectedFile || undefined,
                prospectusUrlInput.trim() || undefined,
                (msg) => {
                    setLoadingMessage(msg);
                    if (msg.includes("HKEX")) {
                        startProgressSimulation();
                    }
                }
            );

            setData(result);
            saveToHistory(result);

            // Reset scroll
            window.scrollTo(0, 0);
        } catch (err) {
            setError(err instanceof Error ? err.message : 'Analysis failed. Please try again.');
        } finally {
            stopProgressSimulation();
            setLoading(false);
        }
    };

    const handleExportMarkdown = () => {
        if (!data) return;
        const md = generateMarkdown(data);
        downloadFile(md, `${data.companyName}_Report.md`, 'text/markdown');
    };

    const handleExportWord = () => {
        if (!data) return;
        const html = generateWordHTML(data);
        downloadFile(html, `${data.companyName}_Report.doc`, 'application/msword');
    };

    const handlePrintPDF = () => {
        window.print();
    };

    return (
        <div className="min-h-screen bg-slate-50 pb-12 relative">
            {/* Header */}
            <header className="bg-slate-900 text-white shadow-lg sticky top-0 z-50 no-print">
                <div className="max-w-[1400px] mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
                    <div className="flex items-center gap-2 cursor-pointer" onClick={() => setData(null)}>
                        <div className="bg-blue-600 p-1.5 rounded-lg">
                            <svg className="w-5 h-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                            </svg>
                        </div>
                        <div>
                            <h1 className="text-lg font-bold tracking-tight leading-none">港股 IPO 智核</h1>
                            <p className="text-[10px] text-slate-400 font-medium tracking-wide uppercase">Institutional Decision Engine</p>
                        </div>
                    </div>
                    <div className="flex items-center gap-4">
                        {/* Admin Link */}
                        {profile?.role === 'admin' && (
                            <Link to="/admin" className="text-xs font-bold text-amber-400 hover:text-amber-300 border border-amber-400/30 px-2 py-1 rounded bg-amber-400/10">
                                Admin Panel
                            </Link>
                        )}

                        {/* User Profile / Logout */}
                        <div className="flex items-center gap-3 pl-4 border-l border-slate-700">
                            <div className="text-right hidden sm:block">
                                <p className="text-xs text-slate-400">Welcome,</p>
                                <p className="text-xs font-bold text-white max-w-[100px] truncate">{profile?.email || user?.email}</p>
                            </div>
                            <button
                                onClick={() => signOut()}
                                className="text-xs text-slate-400 hover:text-white underline"
                            >
                                Logout
                            </button>
                        </div>

                        {data && (
                            <div className="hidden md:flex items-center gap-2 mr-4">
                                <span className="text-xs text-slate-400">正在分析:</span>
                                <span className="text-sm font-bold text-white bg-slate-800 px-3 py-1 rounded-full border border-slate-700">{data.companyName}</span>
                            </div>
                        )}
                        <button
                            onClick={() => setShowHistory(!showHistory)}
                            className="text-sm font-medium text-slate-300 hover:text-white flex items-center gap-1 transition-colors px-3 py-2 rounded hover:bg-slate-800"
                        >
                            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                            </svg>
                            历史
                        </button>
                        {!data && (
                            <a href="#new-analysis" className="bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold px-4 py-2 rounded-md transition-colors">
                                + 新建分析
                            </a>
                        )}
                    </div>
                </div>
            </header>

            {/* Welcome Toast */}
            {showWelcome && (
                <div className="fixed top-20 right-4 z-50 animate-fade-in-up">
                    <div className="bg-green-50 border border-green-200 rounded-lg shadow-lg p-4 flex items-start gap-3 max-w-sm">
                        <div className="flex-shrink-0">
                            <svg className="h-5 w-5 text-green-400" viewBox="0 0 20 20" fill="currentColor">
                                <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                            </svg>
                        </div>
                        <div>
                            <h3 className="text-sm font-medium text-green-800">Login Successful</h3>
                            <div className="mt-1 text-sm text-green-700">
                                <p>Welcome back! Your session is active.</p>
                            </div>
                        </div>
                        <button onClick={() => setShowWelcome(false)} className="ml-auto bg-green-50 text-green-500 hover:text-green-700">
                            <svg className="h-4 w-4" fill="currentColor" viewBox="0 0 20 20">
                                <path fillRule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clipRule="evenodd" />
                            </svg>
                        </button>
                    </div>
                </div>
            )}

            {/* Main Content Container */}
            <main className="max-w-[1400px] mx-auto sm:px-6 lg:px-8">

                {/* History Overlay */}
                {showHistory && (
                    <div className="fixed inset-0 z-40 flex justify-end no-print" onClick={() => setShowHistory(false)}>
                        <div className="absolute inset-0 bg-slate-900/50 backdrop-blur-sm"></div>
                        <div className="relative w-full max-w-md bg-white h-full shadow-2xl overflow-y-auto transform transition-transform" onClick={e => e.stopPropagation()}>
                            <div className="p-4 border-b border-gray-100 flex justify-between items-center bg-gray-50">
                                <h2 className="text-lg font-bold text-gray-800">已分析项目</h2>
                                <button onClick={() => setShowHistory(false)} className="text-gray-400 hover:text-gray-600">
                                    <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                                    </svg>
                                </button>
                            </div>
                            <div className="divide-y divide-gray-100">
                                {history.length === 0 ? (
                                    <div className="text-center py-12 text-gray-400">暂无记录</div>
                                ) : (
                                    history.map((record, idx) => (
                                        <div
                                            key={idx}
                                            className="p-5 hover:bg-blue-50 cursor-pointer group transition-colors"
                                            onClick={() => { setData(record); setShowHistory(false); }}
                                        >
                                            <div className="flex justify-between items-start mb-2">
                                                <h3 className="font-bold text-gray-900 text-base">{record.companyName}</h3>
                                                <span className={`inline-block px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider ${record.positionAdvice.recommendation === 'GO' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'
                                                    }`}>
                                                    {record.positionAdvice.recommendation}
                                                </span>
                                            </div>
                                            <div className="flex justify-between items-end">
                                                <div>
                                                    <p className="text-xs text-gray-500 mb-1">{record.stockCode} | {record.sector}</p>
                                                    <p className="text-[10px] text-gray-400">{new Date().toLocaleDateString()}</p>
                                                </div>
                                                <div className="text-right">
                                                    <div className="text-lg font-bold text-slate-700">{record.scoring.totalScore} <span className="text-xs font-normal text-gray-400">/100</span></div>
                                                </div>
                                            </div>
                                            <div className="mt-3 flex justify-end">
                                                <button
                                                    onClick={(e) => deleteHistoryItem(idx, e)}
                                                    className="text-xs text-red-400 hover:text-red-600 opacity-0 group-hover:opacity-100 transition-opacity flex items-center gap-1"
                                                >
                                                    <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" /></svg>
                                                    删除记录
                                                </button>
                                            </div>
                                        </div>
                                    ))
                                )}
                            </div>
                        </div>
                    </div>
                )}

                {/* --- VIEW 1: LOADING STATE (SKELETON) --- */}
                {loading && (
                    <SkeletonDashboard progressMessage={loadingMessage} />
                )}

                {/* --- VIEW 2: EMPTY STATE / SEARCH --- */}
                {!data && !loading && !showHistory && (
                    <div className="max-w-3xl mx-auto mt-12 px-4 animate-fade-in no-print" id="new-analysis">
                        <div className="text-center mb-10">
                            <h2 className="text-3xl font-bold text-slate-800 tracking-tight">智能投研，从这里开始</h2>
                            <p className="text-slate-500 mt-3 text-lg">整合市场情绪、流动性博弈与基本面深度的 AI 决策引擎</p>
                        </div>

                        <div className="bg-white rounded-2xl shadow-xl border border-slate-100 overflow-hidden">
                            <div className="bg-gradient-to-r from-blue-600 to-indigo-700 px-8 py-4">
                                <h3 className="text-white font-medium flex items-center gap-2">
                                    <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
                                    启动新项目分析
                                </h3>
                            </div>
                            <div className="p-8">
                                <form onSubmit={handleAnalyze} className="space-y-6">
                                    <div>
                                        <label htmlFor="company" className="block text-sm font-semibold text-slate-700 mb-2">目标公司</label>
                                        <div className="relative">
                                            <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                                                <svg className="h-5 w-5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>
                                            </div>
                                            <input
                                                id="company"
                                                type="text"
                                                value={companyName}
                                                onChange={(e) => setCompanyName(e.target.value)}
                                                placeholder="输入股票名称或代码 (e.g., 顺丰控股, 09699)"
                                                className="w-full pl-10 pr-4 py-3 rounded-lg border-gray-300 bg-slate-50 border focus:bg-white focus:border-blue-500 focus:ring-blue-500 transition-all shadow-sm"
                                                required
                                            />
                                        </div>
                                    </div>

                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                        <div>
                                            <label htmlFor="subscription" className="block text-sm font-semibold text-slate-700 mb-2">当前认购倍数 <span className="text-gray-400 font-normal">(可选)</span></label>
                                            <input
                                                id="subscription"
                                                type="text"
                                                value={subscriptionMultiple}
                                                onChange={(e) => setSubscriptionMultiple(e.target.value)}
                                                placeholder="e.g. 150x, 5.2倍"
                                                className="w-full px-4 py-3 rounded-lg border-gray-300 bg-slate-50 border focus:bg-white focus:border-blue-500 focus:ring-blue-500 transition-all shadow-sm"
                                            />
                                            <p className="text-xs text-gray-500 mt-1.5 ml-1">用于回拨机制预判与散户情绪分析</p>
                                        </div>
                                        <div>
                                            <label htmlFor="prospectusUrl" className="block text-sm font-semibold text-slate-700 mb-2">招股书链接 <span className="text-gray-400 font-normal">(可选)</span></label>
                                            <input
                                                id="prospectusUrl"
                                                type="url"
                                                value={prospectusUrlInput}
                                                onChange={(e) => setProspectusUrlInput(e.target.value)}
                                                placeholder="PDF 或 港交所 链接"
                                                className="w-full px-4 py-3 rounded-lg border-gray-300 bg-slate-50 border focus:bg-white focus:border-blue-500 focus:ring-blue-500 transition-all shadow-sm"
                                            />
                                        </div>
                                    </div>

                                    <div>
                                        <label className="block text-sm font-semibold text-slate-700 mb-2">上传材料 <span className="text-gray-400 font-normal">(支持 PDF/Word/Excel)</span></label>
                                        <div className="mt-1 flex justify-center px-6 pt-5 pb-6 border-2 border-gray-300 border-dashed rounded-lg hover:bg-slate-50 transition-colors bg-slate-50/50">
                                            <div className="space-y-1 text-center">
                                                <svg className="mx-auto h-12 w-12 text-gray-400" stroke="currentColor" fill="none" viewBox="0 0 48 48" aria-hidden="true">
                                                    <path d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                                                </svg>
                                                <div className="flex text-sm text-gray-600 justify-center">
                                                    <label htmlFor="file-upload" className="relative cursor-pointer bg-white rounded-md font-medium text-blue-600 hover:text-blue-500 focus-within:outline-none focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-blue-500 px-2">
                                                        <span>选择文件</span>
                                                        <input id="file-upload" name="file-upload" type="file" className="sr-only" onChange={handleFileChange} accept=".pdf,.ppt,.pptx,.doc,.docx,.xls,.xlsx" />
                                                    </label>
                                                    <p className="pl-1">或拖拽文件至此</p>
                                                </div>
                                                <p className="text-xs text-gray-500">{selectedFile ? `已选: ${selectedFile.name}` : '文件大小不超过 10MB'}</p>
                                            </div>
                                        </div>
                                    </div>

                                    <button
                                        type="submit"
                                        disabled={loading}
                                        className="w-full flex justify-center py-3.5 px-4 border border-transparent rounded-lg shadow-sm text-sm font-bold text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
                                    >
                                        {loading ? '分析引擎运行中...' : '生成深度投研报告'}
                                    </button>
                                </form>
                            </div>
                        </div>
                        {error && (
                            <div className="mt-6 bg-red-50 border-l-4 border-red-500 text-red-700 p-4 rounded shadow-sm">
                                <p className="font-bold">分析失败</p>
                                <p>{error}</p>
                            </div>
                        )}
                    </div>
                )}

                {/* --- VIEW 3: REPORT DASHBOARD (3-COLUMN LAYOUT) --- */}
                {data && !loading && (
                    <div className="animate-fade-in px-4 lg:px-0">

                        {/* Toolbar (Mobile only, desktop uses header or sidebar actions) */}
                        <div className="flex justify-between items-center mb-6 lg:hidden no-print">
                            <button onClick={() => setData(null)} className="flex items-center gap-1 text-sm text-slate-600 bg-white border px-3 py-1.5 rounded shadow-sm">
                                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" /></svg>
                                返回搜索
                            </button>
                            <div className="flex gap-2">
                                <button onClick={handleExportMarkdown} className="p-2 bg-white border rounded shadow-sm text-gray-600"><svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg></button>
                                <button onClick={handlePrintPDF} className="p-2 bg-white border rounded shadow-sm text-gray-600"><svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" /></svg></button>
                            </div>
                        </div>

                        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">

                            {/* 1. LEFT SIDEBAR (Navigation) */}
                            <aside className="hidden lg:block lg:col-span-2 sticky top-24 no-print">

                                <button
                                    onClick={() => setData(null)}
                                    className="w-full mb-6 flex items-center justify-center gap-2 px-4 py-2 bg-white border border-slate-200 text-slate-600 font-medium rounded-lg hover:bg-slate-50 hover:text-blue-600 transition-colors shadow-sm"
                                >
                                    <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
                                    </svg>
                                    返回搜索
                                </button>

                                <nav className="space-y-1">
                                    <p className="px-4 text-xs font-semibold text-gray-400 uppercase tracking-wider mb-2">报告目录</p>
                                    <NavItem id="summary" label="1. 决策摘要" active={activeSection === 'summary'} />
                                    <NavItem id="radar" label="2. 智能 Radar" active={activeSection === 'radar'} />
                                    <NavItem id="liquidity" label="3. 流动性博弈" active={activeSection === 'liquidity'} />
                                    <NavItem id="capital" label="4. 资本结构与发行" active={activeSection === 'capital'} />
                                    <NavItem id="risks" label="5. 风险与合规" active={activeSection === 'risks'} />
                                    <NavItem id="business" label="6. 商业基本面" active={activeSection === 'business'} />
                                    <NavItem id="financials" label="7. 财务分析" active={activeSection === 'financials'} />
                                    <NavItem id="valuation" label="8. 估值锚定" active={activeSection === 'valuation'} />
                                    <NavItem id="scenarios" label="9. 情景推演" active={activeSection === 'scenarios'} />
                                    <NavItem id="exit" label="10. 退出策略" active={activeSection === 'exit'} />
                                </nav>

                                <div className="mt-8 px-4">
                                    <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-3">操作</p>
                                    <div className="space-y-2">
                                        <button onClick={handleExportMarkdown} className="w-full text-left text-sm text-gray-600 hover:text-blue-600 flex items-center gap-2">
                                            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
                                            导出 Markdown
                                        </button>
                                        <button onClick={handleExportWord} className="w-full text-left text-sm text-gray-600 hover:text-blue-600 flex items-center gap-2">
                                            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" /></svg>
                                            导出 Word
                                        </button>
                                        <button onClick={handlePrintPDF} className="w-full text-left text-sm text-gray-600 hover:text-blue-600 flex items-center gap-2">
                                            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" /></svg>
                                            打印 / PDF
                                        </button>
                                    </div>
                                </div>
                            </aside>

                            {/* 2. CENTER CONTENT (Deep Dive) */}
                            <div className="lg:col-span-7 space-y-8 print-full-width">

                                {/* Header Card */}
                                <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6 relative overflow-hidden" id="summary">
                                    <div className="absolute top-0 right-0 w-32 h-32 bg-blue-50 rounded-bl-full -mr-8 -mt-8 z-0"></div>
                                    <div className="relative z-10">
                                        <div className="flex justify-between items-start">
                                            <div>
                                                <div className="flex items-center gap-3">
                                                    <h1 className="text-2xl font-bold text-gray-900 tracking-tight">{data.companyName}</h1>
                                                    <span className="px-2 py-0.5 rounded text-xs font-bold bg-gray-100 text-gray-600 border border-gray-200">{data.stockCode}</span>
                                                    <span className="px-2 py-0.5 rounded text-xs font-bold bg-blue-50 text-blue-700 border border-blue-100">{data.sector}</span>
                                                </div>
                                                <div className="flex flex-wrap items-center gap-x-4 gap-y-1 mt-3 text-sm text-gray-600">
                                                    <div className="flex items-center gap-1.5 bg-gray-50 px-2 py-1 rounded border border-gray-100">
                                                        <svg className="w-4 h-4 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" /></svg>
                                                        <span className="font-semibold">{data.listingDate} (预计上市)</span>
                                                    </div>
                                                    <div className="flex items-center gap-1.5 bg-gray-50 px-2 py-1 rounded border border-gray-100">
                                                        <svg className="w-4 h-4 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                                                        <span>定价: <span className="font-semibold text-gray-900">{data.priceRange}</span></span>
                                                    </div>
                                                    <div className="flex items-center gap-1.5 bg-gray-50 px-2 py-1 rounded border border-gray-100">
                                                        <svg className="w-4 h-4 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" /></svg>
                                                        <span>市值: <span className="font-semibold text-gray-900">{data.marketCap}</span></span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="text-right hidden sm:block">
                                                {data.prospectusUrl && (
                                                    <a href={data.prospectusUrl} target="_blank" rel="noreferrer" className="text-xs text-blue-600 hover:underline flex items-center justify-end gap-1">
                                                        招股书
                                                        <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" /></svg>
                                                    </a>
                                                )}
                                            </div>
                                        </div>

                                        <div className="mt-6 flex flex-wrap gap-4">
                                            {data.preIpo.underwriters.slice(0, 3).map((u, i) => (
                                                <span key={i} className="text-xs px-2 py-1 bg-gray-50 border border-gray-200 rounded text-gray-600">{u}</span>
                                            ))}
                                            {data.preIpo.underwriters.length > 3 && <span className="text-xs px-2 py-1 text-gray-400">+{data.preIpo.underwriters.length - 3}</span>}
                                        </div>
                                    </div>
                                </div>

                                {/* Main Modules */}
                                <section id="radar" className="scroll-mt-24">
                                    {data.ipoRadar && <IPORadar data={data.ipoRadar} />}
                                </section>

                                <section id="liquidity" className="scroll-mt-24">
                                    <ProLock tier={profile?.tier}>
                                        {data.liquidityAnalysis && <LiquidityRiskCard data={data.liquidityAnalysis} />}
                                    </ProLock>
                                </section>

                                <section id="capital" className="scroll-mt-24">
                                    <CapitalStructureCard data={data} />
                                </section>

                                <section id="risks" className="scroll-mt-24">
                                    <ProLock tier={profile?.tier}>
                                        <HealthCard items={data.healthCheck} />
                                    </ProLock>
                                </section>

                                <section id="business" className="scroll-mt-24 bg-white rounded-xl shadow-sm border border-gray-200 p-6">
                                    <div className="flex items-center gap-2 mb-4 border-b border-gray-100 pb-3">
                                        <h3 className="text-lg font-bold text-gray-900">商业基本面</h3>
                                        <span className="text-xs text-gray-400 font-mono uppercase">Business & Fundamentals</span>
                                    </div>
                                    <div className="prose prose-sm max-w-none text-gray-700">
                                        <p className="leading-relaxed mb-4">{data.business.description}</p>
                                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                            <div className="bg-gray-50 p-3 rounded-lg">
                                                <span className="text-xs font-semibold text-gray-500 uppercase block mb-1">主要产品</span>
                                                <div className="flex flex-wrap gap-1">
                                                    {data.business.mainProducts.map((p, i) => (
                                                        <span key={i} className="text-xs bg-white border border-gray-200 px-2 py-1 rounded">{p}</span>
                                                    ))}
                                                </div>
                                            </div>
                                            <div className="bg-gray-50 p-3 rounded-lg">
                                                <span className="text-xs font-semibold text-gray-500 uppercase block mb-1">行业地位</span>
                                                <p className="text-sm font-medium">{data.business.industryPosition}</p>
                                            </div>
                                        </div>
                                    </div>
                                </section>

                                <section id="financials" className="scroll-mt-24 bg-white rounded-xl shadow-sm border border-gray-200 p-6">
                                    <ProLock tier={profile?.tier}>
                                        <div className="flex items-center justify-between mb-4 border-b border-gray-100 pb-3">
                                            <div>
                                                <h3 className="text-lg font-bold text-gray-900">核心财务</h3>
                                                <span className="text-xs text-gray-400 font-mono uppercase">Financial Health</span>
                                            </div>
                                            <div className="text-right">
                                                <span className="text-xs text-gray-500 mr-1">CAGR:</span>
                                                <span className="text-sm font-bold text-blue-700">{data.financials.cagr || 'N/A'}</span>
                                            </div>
                                        </div>

                                        {/* Financial Table */}
                                        <div className="overflow-x-auto mb-6 border border-gray-100 rounded-lg">
                                            <table className="min-w-full divide-y divide-gray-200 text-sm">
                                                <thead className="bg-gray-50">
                                                    <tr>
                                                        <th className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Metric</th>
                                                        {data.financials.yearlyData && data.financials.yearlyData.length > 0 ? (
                                                            data.financials.yearlyData.map((d, i) => (
                                                                <th key={i} className="px-4 py-3 text-right text-xs font-semibold text-gray-900">{d.year}</th>
                                                            ))
                                                        ) : (
                                                            <th className="px-4 py-3 text-right text-xs font-semibold text-gray-900">Latest</th>
                                                        )}
                                                    </tr>
                                                </thead>
                                                <tbody className="bg-white divide-y divide-gray-100">
                                                    <tr>
                                                        <td className="px-4 py-3 font-medium text-gray-900">营收 (Revenue)</td>
                                                        {data.financials.yearlyData && data.financials.yearlyData.length > 0 ? (
                                                            data.financials.yearlyData.map((d, i) => (
                                                                <td key={i} className="px-4 py-3 text-right text-gray-700">{d.revenue}</td>
                                                            ))
                                                        ) : (
                                                            <td className="px-4 py-3 text-right text-gray-700">{data.financials.revenue || '-'}</td>
                                                        )}
                                                    </tr>
                                                    <tr>
                                                        <td className="px-4 py-3 font-medium text-gray-900">净利润 (Net Profit)</td>
                                                        {data.financials.yearlyData && data.financials.yearlyData.length > 0 ? (
                                                            data.financials.yearlyData.map((d, i) => (
                                                                <td key={i} className="px-4 py-3 text-right text-gray-700">{d.netProfit}</td>
                                                            ))
                                                        ) : (
                                                            <td className="px-4 py-3 text-right text-gray-700">{data.financials.netProfit || '-'}</td>
                                                        )}
                                                    </tr>
                                                    <tr>
                                                        <td className="px-4 py-3 font-medium text-gray-900">毛利率 (Margin)</td>
                                                        {data.financials.yearlyData && data.financials.yearlyData.length > 0 ? (
                                                            data.financials.yearlyData.map((d, i) => (
                                                                <td key={i} className="px-4 py-3 text-right text-gray-700">{d.grossMargin}</td>
                                                            ))
                                                        ) : (
                                                            <td className="px-4 py-3 text-right text-gray-700">{data.financials.grossMargin || '-'}</td>
                                                        )}
                                                    </tr>
                                                    {/* Growth Row if available */}
                                                    {data.financials.yearlyData && data.financials.yearlyData.some(d => d.growthRate) && (
                                                        <tr>
                                                            <td className="px-4 py-3 font-medium text-gray-500 italic">增速 (YoY Growth)</td>
                                                            {data.financials.yearlyData.map((d, i) => (
                                                                <td key={i} className={`px-4 py-3 text-right text-xs font-bold ${d.growthRate?.includes('-') ? 'text-red-500' : 'text-green-600'}`}>
                                                                    {d.growthRate || '-'}
                                                                </td>
                                                            ))}
                                                        </tr>
                                                    )}
                                                </tbody>
                                            </table>
                                        </div>

                                        {/* Revenue Structure */}
                                        {data.financials.revenueStructure && data.financials.revenueStructure.length > 0 && (
                                            <div className="bg-slate-50 rounded-lg p-4 mb-4 border border-slate-100">
                                                <h4 className="text-xs font-bold text-gray-500 uppercase mb-2">收入结构 (Revenue Breakdown)</h4>
                                                <ul className="space-y-1">
                                                    {data.financials.revenueStructure.map((item, idx) => (
                                                        <li key={idx} className="text-sm text-gray-700 flex items-start gap-2">
                                                            <span className="mt-1.5 w-1 h-1 bg-blue-400 rounded-full flex-shrink-0"></span>
                                                            {item}
                                                        </li>
                                                    ))}
                                                </ul>
                                            </div>
                                        )}

                                        <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4">
                                            <p className="text-sm text-yellow-800">
                                                <span className="font-bold mr-1">财务摘要:</span>
                                                {data.financials.summary}
                                            </p>
                                        </div>
                                    </ProLock>
                                </section>

                                <section id="valuation" className="scroll-mt-24">
                                    <ProLock tier={profile?.tier}>
                                        {data.valuation && <ValuationCard data={data.valuation} />}
                                    </ProLock>
                                </section>

                                <section id="scenarios" className="scroll-mt-24">
                                    <ProLock tier={profile?.tier}>
                                        <ScenarioTable scenarios={data.scenarios} />
                                    </ProLock>
                                </section>

                                <section id="exit" className="scroll-mt-24">
                                    <ProLock tier={profile?.tier}>
                                        <TradingPlanCard strategies={data.exitStrategies} />
                                    </ProLock>
                                </section>

                                <div className="text-center text-xs text-gray-400 py-8 no-print">
                                    Report Generated by Gemini 3 • HK IPO Smart Core
                                </div>
                            </div>

                            {/* 3. RIGHT PANEL (Summary & Action) */}
                            <aside className="hidden lg:block lg:col-span-3 sticky top-24 space-y-6">
                                {/* Action Card */}
                                <div className="bg-white rounded-xl shadow-lg border border-indigo-100 overflow-hidden">
                                    <div className="bg-slate-900 p-4 text-center">
                                        <p className="text-xs text-indigo-200 uppercase tracking-widest font-semibold mb-1">AI 综合建议</p>
                                        <div className={`text-3xl font-black tracking-tight ${data.positionAdvice.recommendation === 'GO' ? 'text-green-400' : 'text-red-400'
                                            }`}>
                                            {data.positionAdvice.recommendation}
                                        </div>
                                    </div>
                                    <div className="p-5">
                                        <div className="flex justify-between items-end mb-4 border-b border-gray-100 pb-4">
                                            <span className="text-sm font-medium text-gray-500">量化评分</span>
                                            <span className={`text-3xl font-bold ${data.scoring.totalScore >= 70 ? 'text-green-600' : data.scoring.totalScore >= 50 ? 'text-yellow-600' : 'text-red-600'
                                                }`}>
                                                {data.scoring.totalScore}
                                            </span>
                                        </div>

                                        <p className="text-xs font-semibold text-gray-500 uppercase mb-2">核心逻辑</p>
                                        <p className="text-sm text-gray-800 leading-snug mb-4">
                                            {data.positionAdvice.rationale.length > 100
                                                ? data.positionAdvice.rationale.substring(0, 100) + '...'
                                                : data.positionAdvice.rationale}
                                        </p>

                                        <div className="bg-gray-50 rounded p-3 text-center">
                                            <span className="text-xs text-gray-400 block mb-1">最大回撤预算</span>
                                            <span className="font-bold text-gray-900">{data.positionAdvice.maxDrawdownTolerance}</span>
                                        </div>
                                    </div>
                                </div>

                                {/* Quick Risks / Health */}
                                <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
                                    <div className="bg-gray-50 px-4 py-2 border-b border-gray-200">
                                        <h4 className="text-xs font-bold text-gray-700 uppercase">关键风险项 (Red Flags)</h4>
                                    </div>
                                    <div className="p-4">
                                        {data.healthCheck.filter(h => h.status !== 'GREEN').length > 0 ? (
                                            <ul className="space-y-3">
                                                {data.healthCheck.filter(h => h.status !== 'GREEN').map((h, i) => (
                                                    <li key={i} className="flex items-start gap-2">
                                                        <span className="mt-1 flex-shrink-0 w-1.5 h-1.5 rounded-full bg-red-500"></span>
                                                        <div>
                                                            <span className="text-xs font-bold text-gray-800 block">{h.label}</span>
                                                            <span className="text-[10px] text-gray-500 leading-tight block">{h.issue || h.value}</span>
                                                        </div>
                                                    </li>
                                                ))}
                                            </ul>
                                        ) : (
                                            <div className="text-center py-4 text-green-600 text-sm">
                                                <span className="block text-2xl mb-1">✓</span>
                                                暂无重大风险项
                                            </div>
                                        )}
                                    </div>
                                </div>

                                <div className="bg-gradient-to-br from-blue-600 to-indigo-700 rounded-xl p-4 text-white shadow-md">
                                    <p className="text-xs text-blue-200 uppercase mb-1">基石解禁倒计时</p>
                                    <p className="font-mono text-lg font-bold">6 Months</p>
                                    <p className="text-[10px] text-blue-100 mt-2 opacity-80">自上市日起算，请关注日历提醒。</p>
                                </div>

                            </aside>

                        </div>

                        {/* Chat Assistant */}
                        <ResearchAssistant data={data} />
                    </div>
                )
                }
            </main >
        </div >
    );
};

export default Dashboard;